<div class="flex w-full items-center justify-between outline">
	<div class="h-8 w-8 bg-red-400" />
	<div class="to h-8 w-full bg-orange-400 bg-gradient-to-r from-red-400" />
	<div class="h-8 w-8 bg-orange-400" />
	<div class="h-8 w-3 bg-black" />
	<div class="to h-8 w-full bg-yellow-400 bg-gradient-to-r from-orange-400" />
	<div class="h-8 w-8 bg-yellow-400" />
	<div class="to h-8 w-full bg-green-400 bg-gradient-to-r from-yellow-400" />
	<div class="h-8 w-8 bg-green-400" />
	<div class="h-8 w-3 bg-black" />
	<div class="to h-8 w-full bg-cyan-400 bg-gradient-to-r from-green-400" />
	<div class="h-8 w-8 bg-cyan-400" />
	<div class="h-8 w-3 bg-black" />
	<div class="to h-8 w-full bg-blue-400 bg-gradient-to-r from-cyan-400" />
	<div class="h-8 w-3 bg-black" />
	<div class="h-8 w-8 bg-blue-400" />
	<div class="h-8 w-3 bg-black" />
	<div class="to h-8 w-full bg-purple-400 bg-gradient-to-r from-blue-400" />
	<div class="h-8 w-8 bg-purple-400" />
</div>
